apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-bvys
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-bvys
    app.kubernetes.io/part-of: test-app-878
  name: maven-hello-world-bvys
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-bvys
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-bvys
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-878/maven-hello-world-bvys@sha256:70397566403ef42f2fffe7b102a8a35775799a70eb416dd82bf3eeb4992bad2e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
