apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-624f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-624f
    app.kubernetes.io/part-of: test-app-878
  name: e2e-tests-parent-image-with-digest-only-624f
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-624f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-624f
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-878/e2e-tests-parent-image-with-digest-only-624f@sha256:426c1fc35d4bda8229bed845f2a47a76ce8ce093eebeb80c8bc92af3ba657640
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
