apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-8dot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-8dot
    app.kubernetes.io/part-of: test-app-878
  name: nodejs-no-dockerfile-8dot
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-8dot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-8dot
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-878/nodejs-no-dockerfile-8dot@sha256:d85fbad9e29bfa86da5279966f573f87e185f39937520464e2229f50f01dc2da
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
