apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-0tik
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-0tik
    app.kubernetes.io/part-of: test-app-878
  name: pip-e2e-test-0tik
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-0tik
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-0tik
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-878/pip-e2e-test-0tik@sha256:65a3b136c5c2e0ce15cb075710e2b79b1b008fec6395bc19b27245a88ef8c5b0
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
