apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-apxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-from-registry-rh-io-apxy
    app.kubernetes.io/part-of: test-app-878
  name: e2e-tests-parent-image-from-registry-rh-io-apxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-apxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-apxy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-878/e2e-tests-parent-image-from-registry-rh-io-apxy@sha256:f60422645ec214b185ccbb1b8ff40644912d1ba68d24365589b69d554a43954a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
