apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-yxxc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-yxxc
    app.kubernetes.io/part-of: test-app-878
  name: fbc-sample-repo-yxxc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-yxxc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-yxxc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-878/fbc-sample-repo-yxxc@sha256:9840ce413b60aa9031c10717a456690c3ab4cbdda7c13274624cd5a0f6d700d7
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
